#!/bin/bash

set -e

if [ "$1" = "" ]; then
    echo "Usage: $0 GITHUB_USERNAME"
    exit 1
else
    KEYS=$(curl -s https://github.com/$1.keys)
    # TODO: some kind of error checking?
    echo "$KEYS" >> $HOME/.ssh/authorized_keys
fi
